config/routes.rb
Rails.application.routes.draw do
  resources :tuits
  get 'site/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "site#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tuit.rb
class Tuit < ApplicationRecord

  def self.search(search)
    if search  
      find(:all, :conditions => ['description LIKE ?', "%#{search}%"])  
    else  
      find(:all)  
    end  
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end
end

app/controllers/tuits_controller.rb
class TuitsController < ApplicationController
  before_action :set_tuit, only: %i[ show edit update destroy ]

  # GET /tuits or /tuits.json
  def index
    if params[:search].present?
      @pagy, @tuits = pagy(Tuit.where("user_name LIKE ? OR description LIKE ?", "\%#{params[:search]}\%", "\%#{params[:search]}\%"), items: 10)
    else      
      @pagy, @tuits = pagy((Tuit.all.order(created: :desc)), items: 10)
    end    
    
  end

  # GET /tuits/1 or /tuits/1.json
  def show
  end

  # GET /tuits/new
  def new
    @tuit = Tuit.new
  end

  # GET /tuits/1/edit
  def edit
  end

  # POST /tuits or /tuits.json
  def create
    @tuit = Tuit.new(tuit_params)

    respond_to do |format|
      if @tuit.save
        format.html { redirect_to tuit_url(@tuit), notice: "Tuit was successfully created." }
        format.json { render :show, status: :created, location: @tuit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tuit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tuits/1 or /tuits/1.json
  def update
    respond_to do |format|
      if @tuit.update(tuit_params)
        format.html { redirect_to tuit_url(@tuit), notice: "Tuit was successfully updated." }
        format.json { render :show, status: :ok, location: @tuit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tuit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tuits/1 or /tuits/1.json
  def destroy
    @tuit.destroy

    respond_to do |format|
      format.html { redirect_to tuits_url, notice: "Tuit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tuit
      @tuit = Tuit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tuit_params
      params.require(:tuit).permit(:description, :user_name, :location, :friends_count, :created, :content, :search)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/tuits_helper.rb
module TuitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTuiter</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body id="page-top">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
      <div class="container px-4">
        <a class="navbar-brand" href="<%= root_path %>#page-top"><i class="bi bi-twitter" style="color: #ffffff;"></i><span>Tuiter</span></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ms-auto">
            <li class="nav-item"><%= link_to "Tuits", tuits_path, :class=>"nav-link" %></li>
            <li class="nav-item"><a class="nav-link" href="<%= root_path %>#about">About</a></li>
            <li class="nav-item"><a class="nav-link" href="<%= root_path %>#services">Services</a></li>
            <li class="nav-item"><a class="nav-link" href="<%= root_path %>#contact">Contact</a></li>
          </ul>
        </div>
      </div>
    </nav>
    <%= yield %>
    
  </body>
</html>

app/views/site/index.html.erb
<!-- Header-->
<header class="bg-primary bg-gradient text-white">
    <div class="container px-4 text-center">
        <h1 class="fw-bolder">Welcome to Tuiter</h1>
        <p class="lead">A nostalgic site for those who miss twitter... ejem X</p>
        <a class="btn btn-lg btn-light" href="#about">Tuitea!</a>
    </div>
</header>
<!-- About section-->
<section id="about">
    <div class="container px-4">
        <div class="row gx-4 justify-content-center">
            <div class="col-lg-8">
                <h2>About this page</h2>
                <p class="lead">We will not lie, this is a fake site, but its a try.</p>
                <ul>
                    <li>This is not tweeter</li>
                    <li>No tweets on this site</li>
                    <li>Just nice scrolling</li>
                    <li>Use it as you want</li>
                </ul>
            </div>
        </div>
    </div>
</section>
<!-- Services section-->
<section class="bg-light" id="services">
    <div class="container px-4">
        <div class="row gx-4 justify-content-center">
            <div class="col-lg-8">
                <h2>Services we offer</h2>
                <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut optio velit inventore, expedita quo laboriosam possimus ea consequatur vitae, doloribus consequuntur ex. Nemo assumenda laborum vel, labore ut velit dignissimos.</p>
            </div>
        </div>
    </div>
</section>
<!-- Contact section-->
<section id="contact">
    <div class="container px-4">
        <div class="row gx-4 justify-content-center">
            <div class="col-lg-8">
                <h2>Contact us</h2>
                <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero odio fugiat voluptatem dolor, provident officiis, id iusto! Obcaecati incidunt, qui nihil beatae magnam et repudiandae ipsa exercitationem, in, quo totam.</p>
            </div>
        </div>
    </div>
</section>
<!-- Footer-->
<footer class="py-5 bg-dark">
    <div class="container px-4"><p class="m-0 text-center text-white">No Copyright &copy; Tuiter 2023</p></div>
</footer>

app/views/tuits/_form.html.erb
<%= bootstrap_form_with(model: tuit) do |form| %>
  <% if tuit.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tuit.errors.count, "error") %> prohibited this tuit from being saved:</h2>

      <ul>
        <% tuit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  
  <%= form.text_field :description %>

  
  <%= form.text_field :user_name %>

  
  <%= form.select :location, ["New York", "Los Angeles", "London", "Tokyo", "Paris", "Sydney", "Berlin", "Toronto", "Mumbai", "San Francisco"] %>

  
  <%= form.number_field :friends_count %>

  
  <%= form.datetime_field :created %>

  
  <%= form.text_area :content %>

  <%= form.primary%>
<%end%>  

app/views/tuits/_tuit.html.erb
<li class="tweet-card">
  <div  id="<%= dom_id tuit %>" class="tweet-content">
    <div class="tweet-header">
      <span class="fullname">
        <strong><%= tuit.user_name %></strong>
      </span>
      <span class="tweet-time"><%= tuit.created %></span>
    </div>
    <a>
      <img class="tweet-card-avatar" src="<%= asset_path("default-pfp.png") %>" alt="">
    </a>
    <div class="tweet-text">
      <p class="" lang="es" data-aria-label-part="0"><%= tuit.description %></p>
    </div>
    <div class="tweet-footer">
      <a class="tweet-footer-btn">
        <i class="bi bi-chat-fill"></i><span><%= rand(1000) %></span>
      </a>
      <a class="tweet-footer-btn">
        <i class="bi bi-arrow-repeat"></i><span><%= rand(1000) %></span>
      </a>
      <a class="tweet-footer-btn">
        <i class="bi bi-suit-heart-fill"></i><span><%= rand(1000) %></span>
      </a>
      <a class="tweet-footer-btn">
        <i class="bi bi-envelope"></i><span><%= rand(1000) %></span>
      </a>
    </div>
  </div>
</li>

app/views/tuits/edit.html.erb
<section id="tuit_form">
  <div class="container px-4">
    <div class="row gx-4 justify-content-center">
    <div class="col-lg-8">        
      <div class="text-white px-2 py-3" style="background-image: url('<%= asset_path('background.jpg')%>');">
        <h1>Editing tuit</h1>
      </div>
    </div>
    <div id="tuit_f" class="col-6 py-3">
      <%= render "form", tuit: @tuit %>
      <div>
        <%= link_to "Show this tuit", @tuit %> |
        <%= link_to "Back to tuits", tuits_path %>        
      </div>
    </div>
  </div>

  <br>
  
</section>

app/views/tuits/index.html.erb
<p style="color: green"><%= notice %></p>

<section id="tuits">
  <div class="container px-4">
    <div class="row gx-4 justify-content-center">
    <div class="col-lg-8">        
      <div class="text-white px-2 py-3" style="background-image: url('<%= asset_path('background.jpg')%>');">
        <div class="container-fluid px-2 justify-content-center">
          <h1 class="d-inline mx-2">Tuits</h1>
        </div>  
        <div class="px-2">
          <%= form_tag(tuits_path, :method=>:get) do %>
            <%= text_field_tag :search, params[:search] %>
            <%= submit_tag "Search", class: "btn btn-tuiter py-2" %>
          <% end %>
        </div>
      </div>
      <div id="tuits" class="col-6">
        <ol class="tweet-list">
        <% @tuits.each do |tuit| %>
          <%= render tuit %>
          <div class="container-fluid px-2 justify-content-center">
            <%= link_to "Show", tuit, :class=>"btn btn-follow" %>
            <%= link_to "Edit", edit_tuit_path(tuit) , :class=>"btn btn-follow" %>
            <%= link_to "Destroy", tuit, method: :delete, :class=>"btn btn-follow" %>
          </div>            
        <% end %>
        </ol>
        <div class="py-3"><%= pagy_bootstrap_nav(@pagy).html_safe %></div>
        <%= link_to "New tuit", new_tuit_path, :class=>"btn btn-tuiter py-2" %>
      </div>
    </div>
    </div>
  </div>
</section>

app/views/tuits/new.html.erb
<section id="tuit_form">
  <div class="container px-4">
    <div class="row gx-4 justify-content-center">
    <div class="col-lg-8">        
      <div class="text-white px-2 py-3" style="background-image: url('<%= asset_path('background.jpg')%>');">
        <h1>New tuit</h1>
      </div>
    </div>
    <div id="tuit_f" class="col-6 py-3">
      <%= render "form", tuit: @tuit %>
    </div>
  </div>

  <br>
  <div>
    <%= link_to "Back to tuits", tuits_path %>
  </div>
</section>

app/views/tuits/show.html.erb
<section id="tuit_form">
  <div class="container px-4">
    <div class="row gx-4 justify-content-center">
    <div class="col-lg-8">    
      <p style="color: green"><%= notice %></p>    
      <div class="text-white px-2 py-3" style="background-image: url('<%= asset_path('background.jpg')%>');">
        <h1>Tuit</h1>
      </div>
    </div>
    <div id="tuit_f" class="col-6 py-3">
      <%= render @tuit %>
      <div>
      <%= link_to "Edit this tuit", edit_tuit_path(@tuit) %> |
      <%= link_to "Back to tuits", tuits_path %>

      <%= button_to "Destroy this tuit", @tuit, method: :delete, class: "btn btn-tuiter py-2" %>
    </div>
    </div>
    <br>
    
  </div>

  
</section>